
name: Compila APK Android

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4

    - name: Imposta Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Imposta Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Installa dipendenze di sistema
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          git wget curl unzip lld \
          autoconf libtool pkg-config \
          zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo5 \
          cmake libffi-dev libssl-dev

    - name: Installa l'ultima versione di Buildozer e Cython
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade cython==0.29.36
        pip install --upgrade git+https://github.com/kivy/buildozer.git@master

    - name: Pre-accetta licenze Android SDK
      run: |
        mkdir -p /home/runner/.buildozer/android/platform/android-sdk/licenses
        echo "24333f8a43b681ff21c2d91dabcb162822052738" > /home/runner/.buildozer/android/platform/android-sdk/licenses/android-sdk-license
        echo "84831b9409646a918e30573bab4c9c91346d8abd" >> /home/runner/.buildozer/android/platform/android-sdk/licenses/android-sdk-license
        echo "d56f5187479451eabf01fb78af6dfcb131a648b0" >> /home/runner/.buildozer/android/platform/android-sdk/licenses/android-sdk-license

    - name: Compila APK
      run: |
        buildozer -v android debug

    - name: Salva l'APK compilato
      uses: actions/upload-artifact@v4
      with:
        name: pacchetto-apk
        path: bin/*.apk
