name: Compila APK Android

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Imposta Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Installa dipendenze di sistema
      run: |
        sudo apt-get update
        sudo apt-get install -y git zip unzip openjdk-17-jdk autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo5 cmake libffi-dev libssl-dev

    - name: Installa Buildozer e Cython
      run: |
        pip install --upgrade pip
        pip install --upgrade buildozer cython

    - name: Compila APK con Buildozer
      uses: ArtemSBulgakov/buildozer-action@v1
      id: buildozer
      with:
        command: buildozer -v android debug
        buildozer_version: master

    - name: Salva l'APK compilato
      uses: actions/upload-artifact@v4
      with:
        name: pacchetto-apk
        path: bin/*.apk
